version: '3.8'

services:
  hotel_api:
    container_name: hotel_api
    image: hotel_api:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis
